export const initialData = {
    boards: [
        {
            id: "board-1",
            columnOrder: ["column-1", "column-2", "column-3"],
            columns: [
                {
                    id: "column-1",
                    boardId: "board-1",
                    title: "To do column",
                    cardOrder: [
                        "card-1",
                        "card-2",
                        "card-3",
                        "card-4",
                        "card-5",
                        "card-6",
                        "card-7",
                        "card-8",
                        "card-9",
                        "card-10",
                        "card-11",
                        "card-12",
                        "card-13",
                        "card-14",
                        "card-15",
                    ],
                    cards: [
                        {
                            id: "card-1",
                            boardId: "board-1",
                            columnId: "column-1",
                            title: "Title of card 1",
                            cover: "https://cdna.artstation.com/p/assets/images/images/029/252/640/large/foritis-wong-true-damage-yasuo-c.jpg?1596947250",
                        },
                        {
                            id: "card-2",
                            boardId: "board-1",
                            columnId: "column-1",
                            title: "Title of card 2",
                            cover: null,
                        },
                        {
                            id: "card-4",
                            boardId: "board-1",
                            columnId: "column-1",
                            title: "Title of card 4",
                            cover: null,
                        },
                        {
                            id: "card-5",
                            boardId: "board-1",
                            columnId: "column-1",
                            title: "Title of card 5",
                            cover: null,
                        },
                        {
                            id: "card-6",
                            boardId: "board-1",
                            columnId: "column-1",
                            title: "Title of card 6",
                            cover: null,
                        },
                        {
                            id: "card-7",
                            boardId: "board-1",
                            columnId: "column-1",
                            title: "Title of card 7",
                            cover: null,
                        },
                        {
                            id: "card-8",
                            boardId: "board-1",
                            columnId: "column-1",
                            title: "Title of card 8",
                            cover: null,
                        },
                        {
                            id: "card-9",
                            boardId: "board-1",
                            columnId: "column-1",
                            title: "Title of card 9",
                            cover: null,
                        },
                        {
                            id: "card-10",
                            boardId: "board-1",
                            columnId: "column-1",
                            title: "Title of card 10",
                            cover: null,
                        },
                        {
                            id: "card-11",
                            boardId: "board-1",
                            columnId: "column-1",
                            title: "Title of card 11",
                            cover: null,
                        },
                        {
                            id: "card-12",
                            boardId: "board-1",
                            columnId: "column-1",
                            title: "Title of card 12",
                            cover: null,
                        },
                        {
                            id: "card-13",
                            boardId: "board-1",
                            columnId: "column-1",
                            title: "Title of card 13",
                            cover: null,
                        },
                        {
                            id: "card-14",
                            boardId: "board-1",
                            columnId: "column-1",
                            title: "Title of card 14",
                            cover: null,
                        },
                        {
                            id: "card-15",
                            boardId: "board-1",
                            columnId: "column-1",
                            title: "Title of card 15",
                            cover: null,
                        },
                    ],
                },
                {
                    id: "column-2",
                    boardId: "board-1",
                    title: "Column 2",
                    cardOrder: ["card-16", "card-17", "card-18"],
                    cards: [
                        {
                            id: "card-16",
                            boardId: "board-1",
                            columnId: "column-2",
                            title: "Title of card 16",
                            cover: null,
                        },
                        {
                            id: "card-17",
                            boardId: "board-1",
                            columnId: "column-2",
                            title: "Title of card 17",
                            cover: null,
                        },
                        {
                            id: "card-18",
                            boardId: "board-1",
                            columnId: "column-2",
                            title: "Title of card 18",
                            cover: "https://s3.cloud.cmctelecom.vn/tinhte2/2020/11/5220269_cover.jpg",
                        },
                    ],
                },
                {
                    id: "column-3",
                    boardId: "board-1",
                    title: "Column 3",
                    cardOrder: ["card-19", "card-20", "card-21"],
                    cards: [
                        {
                            id: "card-19",
                            boardId: "board-1",
                            columnId: "column-3",
                            title: "Title of card 19",
                            cover: null,
                        },
                        {
                            id: "card-20",
                            boardId: "board-1",
                            columnId: "column-3",
                            title: "Title of card 20",
                            cover: null,
                        },
                        {
                            id: "card-21",
                            boardId: "board-1",
                            columnId: "column-3",
                            title: "Title of card 21",
                            cover: null,
                        },
                    ],
                },
            ],
        },
    ],
};
